#!/bin/bash

echo "Proiect AEACD - Binarizare prin Votare"
echo "Atanasiu Alexandru-Marian, Damian Petrisor Alin, Panaitescu Cristian"

# rm bin/*
# python src/main.py data/sample1.png bin/sample1_bin.png
# python src/main.py data/sample2.png bin/sample2_bin.png
# python src/main.py data/sample3.png bin/sample3_bin.png
# python src/main.py data/sample4.png bin/sample4_bin.png

echo "" > ./masuratori.csv
totalFiles=$(ls -l bin/*.png | wc -l)
echo $totalFiles
currentFileCount=0
for filename in bin/*.png; do
    python src/evaluation.py "$filename" >> ./masuratori.csv
    currentFileCount=$((currentFileCount+1))
    echo $currentFileCount / $totalFiles
done

#bcompare data/sample1.png bin/sample1_bin.png
