#!/bin/bash

echo "Proiect AEACD - Binarizare prin Votare"
echo "Atanasiu Alexandru-Marian, Damian Petrisor Alin, Panaitescu Cristian"

python3 src/main.py data/sample1.png bin/sample1_bin.png
bcompare data/sample1.png bin/sample1_bin.png